# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-core-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish snapcraft stable on core
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: stable
        build_args: SNAPCRAFT_CHANNEL=stable,UBUNTU_VERSION=16.04

    - name: Publish snapcraft beta on core
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: beta
        build_args: SNAPCRAFT_CHANNEL=beta,UBUNTU_VERSION=16.04

    - name: Publish snapcraft candidate on core
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: candidate
        build_args: SNAPCRAFT_CHANNEL=candidate,UBUNTU_VERSION=16.04

    - name: Publish snapcraft edge on core
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: edge
        build_args: SNAPCRAFT_CHANNEL=edge,UBUNTU_VERSION=16.04

  deploy-core18-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish snapcraft stable on core18
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: stable-core18
        build_args: SNAPCRAFT_CHANNEL=stable,UBUNTU_VERSION=18.04

    - name: Publish snapcraft beta on core18
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: beta-core18
        build_args: SNAPCRAFT_CHANNEL=beta,UBUNTU_VERSION=18.04

    - name: Publish snapcraft candidate on core18
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: candidate-core18
        build_args: SNAPCRAFT_CHANNEL=candidate,UBUNTU_VERSION=18.04

    - name: Publish snapcraft edge on core18
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cjp256/snapcraft-docker-image
        tags: edge-core18
        build_args: SNAPCRAFT_CHANNEL=edge,UBUNTU_VERSION=18.04
